1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [8]:
import numpy as np
import pandas as pd

In [9]:
data = {
    'Date': [
        '2026-01-01', '2026-01-01', '2026-01-01',
        '2026-01-02', '2026-01-02', '2026-01-02',
        '2026-01-03', '2026-01-03'
    ],
    'Category': [
        'Food', 'Clothing', 'Food',
        'Food', 'Clothing', 'Electronics',
        'Clothing', 'Food'
    ],
    'Value': [
        100, 200, 50, 150, 300, 400, 250, 80
    ]
}

df = pd.DataFrame(data)
display(df)

         Date     Category  Value
0  2026-01-01         Food    100
1  2026-01-01     Clothing    200
2  2026-01-01         Food     50
3  2026-01-02         Food    150
4  2026-01-02     Clothing    300
5  2026-01-02  Electronics    400
6  2026-01-03     Clothing    250
7  2026-01-03         Food     80

In [12]:
pivot = pd.pivot_table(
    df,
    values='Value',
    index='Category',
    columns='Date',
    aggfunc='sum',
    fill_value=0
)
display(pivot)

Date         2026-01-01  2026-01-02  2026-01-03
Category
Clothing            200         300         250
Electronics           0         400           0
Food                150         150          80