1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [1]:
import numpy as np
import pandas as pd

In [9]:
arr = np.random.randint(1, 31, size=(5, 3))
print(arr)

[[30  2 15]
 [19 27 20]
 [ 6 17 16]
 [ 5  1 16]
 [19  2 30]]

In [11]:
columns = ["A", "B", "C"]
df = pd.DataFrame(arr, columns=columns).astype(float)
display(df)

      A     B     C
0  30.0   2.0  15.0
1  19.0  27.0  20.0
2   6.0  17.0  16.0
3   5.0   1.0  16.0
4  19.0   2.0  30.0

In [12]:
df.loc[1, "A"] = np.nan
df.loc[3, "B"] = np.nan
df.loc[4, "C"] = np.nan
display(df)

      A     B     C
0  30.0   2.0  15.0
1   NaN  27.0  20.0
2   6.0  17.0  16.0
3   5.0   NaN  16.0
4  19.0   2.0   NaN

In [13]:
means = df.mean()
print(means)

A    15.00
B    12.00
C    16.75
dtype: float64

In [17]:
filled = df.fillna(means)
display(filled)

      A     B      C
0  30.0   2.0  15.00
1  15.0  27.0  20.00
2   6.0  17.0  16.00
3   5.0  12.0  16.00
4  19.0   2.0  16.75