2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.random.randint(1, 31, size=(6, 4))
print(arr)

[[27 24  6 20]
 [24 20 21  6]
 [14  9 30 28]
 [22  2 28 15]
 [25  8 12  3]
 [30 25  7 20]]

In [5]:
columns = list("ABCD")
df = pd.DataFrame(arr, columns=columns).astype(float)
display(df)

      A     B     C     D
0  27.0  24.0   6.0  20.0
1  24.0  20.0  21.0   6.0
2  14.0   9.0  30.0  28.0
3  22.0   2.0  28.0  15.0
4  25.0   8.0  12.0   3.0
5  30.0  25.0   7.0  20.0

In [6]:
df.loc[1, "A"] = np.nan
df.loc[4, "D"] = np.nan
display(df)

      A     B     C     D
0  27.0  24.0   6.0  20.0
1   NaN  20.0  21.0   6.0
2  14.0   9.0  30.0  28.0
3  22.0   2.0  28.0  15.0
4  25.0   8.0  12.0   NaN
5  30.0  25.0   7.0  20.0

In [9]:
droped_df = df.dropna()
display(droped_df)

      A     B     C     D
0  27.0  24.0   6.0  20.0
2  14.0   9.0  30.0  28.0
3  22.0   2.0  28.0  15.0
5  30.0  25.0   7.0  20.0