1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "ID": (1, 2, 3, 4),
    "Name": ("Sunjir", "Azim", "Karim", "Arafat")
})

df2 = pd.DataFrame({
    "ID": (1, 2, 3, 4),
    "Mark": (80, 94, 100, 50)
})

display(df1)
display(df2)

   ID    Name
0   1  Sunjir
1   2    Azim
2   3   Karim
3   4  Arafat

   ID  Mark
0   1    80
1   2    94
2   3   100
3   4    50

In [3]:
df_merged = pd.merge(df1, df2, on="ID")
display(df_merged)

   ID    Name  Mark
0   1  Sunjir    80
1   2    Azim    94
2   3   Karim   100
3   4  Arafat    50