2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "Name": ("Sunjir", "Azim", "Karim", "Arafat"),
    "Age": (21, 21, 23, 20)
})

df2 = pd.DataFrame({
    "City": ("Sylhet", "Korea", "Dhaka", "London"),
    "Mark": (90, 95, 80, 100)
})

display(df1)
display(df2)

     Name  Age
0  Sunjir   21
1    Azim   21
2   Karim   23
3  Arafat   20

     City  Mark
0  Sylhet    90
1   Korea    95
2   Dhaka    80
3  London   100

In [4]:
row_wise = pd.concat([df1, df2], axis=0)
column_wise = pd.concat([df1, df2], axis=1)
display(row_wise)
display(column_wise)

     Name   Age    City   Mark
0  Sunjir  21.0     NaN    NaN
1    Azim  21.0     NaN    NaN
2   Karim  23.0     NaN    NaN
3  Arafat  20.0     NaN    NaN
0     NaN   NaN  Sylhet   90.0
1     NaN   NaN   Korea   95.0
2     NaN   NaN   Dhaka   80.0
3     NaN   NaN  London  100.0

     Name  Age    City  Mark
0  Sunjir   21  Sylhet    90
1    Azim   21   Korea    95
2   Karim   23   Dhaka    80
3  Arafat   20  London   100