2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [1]:
import numpy as np
import pandas as pd

In [3]:
dates  = pd.date_range("2021-01-01", "2021-12-31", freq="D")
arr = np.random.randint(1, 100, size=len(dates))

df = pd.DataFrame(arr, index=dates).astype(float)
display(df.head())

               0
2021-01-01  13.0
2021-01-02  62.0
2021-01-03  29.0
2021-01-04  79.0
2021-01-05  65.0

In [5]:
df["Rolling Mean"] = df[0].rolling(window=7).mean()
display(df.head(10))

               0  Rolling Mean
2021-01-01  13.0           NaN
2021-01-02  62.0           NaN
2021-01-03  29.0           NaN
2021-01-04  79.0           NaN
2021-01-05  65.0           NaN
2021-01-06   1.0           NaN
2021-01-07  92.0     48.714286
2021-01-08  80.0     58.285714
2021-01-09  93.0     62.714286
2021-01-10  88.0     71.142857