2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [1]:
import numpy as np
import pandas as pd

In [3]:
arr = np.random.randint(1, 100, size=(6, 3))
df = pd.DataFrame(
    arr,
    columns=['A', 'B', 'C']
)
display(df)

    A   B   C
0  16  89   7
1  76  81  44
2  54  77   8
3   6   5  42
4  51  32  18
5  86  44   7

In [4]:
df['Sum'] = df.apply(lambda row: row['A'] + row['B'] + row['C'], axis=1)
display(df)

    A   B   C  Sum
0  16  89   7  112
1  76  81  44  201
2  54  77   8  139
3   6   5  42   53
4  51  32  18  101
5  86  44   7  137